# Generated by Django 5.0.7 on 2024-07-17 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tasktype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='worker',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
