# Generated by Django 4.1 on 2024-07-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0003_alter_project_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
